resource_group_name       = "ramyarg"
location                  = "East US"
vnet_name                 = "ramya-dev-vnet"
vnet_address_space        = "10.0.0.0/16"
subnet_name               = "ramya-dev-subnet"
subnet_address_prefix     = "10.0.1.0/24"
nic_name                  = "ramya-dev-nic"
vm_name                   = "ramya-dev-vm"
vm_size                   = "Standard_B1s"
admin_username            = "azureuser"
admin_password            = "P@ssword1234!"
storage_account_name      = "ramyadevstorage"

backend_rg                = "ramyarg"
backend_storage_account   = "ramyadevstorage"
backend_container         = "tfstate"
backend_key               = "dev.terraform.tfstate"
